### ISSUE TITLE
prepare script does not read env_variables

### ISSUE THREAD

**Issue by pnicorelli** [GoogleCloudPlatform/nodejs-docs-samples#1497]
Hi all,

I'm not sure this issue is ONTOPIC, I just use some code from your example. 

I have some issue to get the `process.env` from a prepare script in package.json.
I'm trying to run mysql migration before starting the app but I can not fetch the process.env variables

My `package.json`

```json
...
  "scripts": {
     ...
    "prepare": "npm run gcp-build",
    "gcp-build": "node migrations.js",
  },
...
```

My `migrations.js`
```js
var path = require('path')
var mysql = require('mysql')
var migration = require('mysql-migrations')

require('dotenv').config()

var connection = mysql.createPool({
  connectionLimit: 10,
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASS,
  database: process.env.DB_NAME
})

migration.init(connection, path.join(__dirname, '/migrations'))
```

My app read the env_variables from app.yaml without problem but the prepare script do not.

Any help will be appreciated.

**Comment by fhinkel** [comment]
@pnicorelli Thanks for posting the issue. Could you post your `app.yaml` as well? I don't see why the script wouldn't pick up the variables when the app can.

**Comment by pnicorelli** [comment]
Hi @fhinkel, thanks for your reply

app.yaml

```yaml
runtime: nodejs10
service: xxxxxx-api

includes:
  - env_variables.yaml

```
env_variables.yaml
```yaml
env_variables:
  NODE_ENV: "production"
  CLIENT_ID: "xxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com"
  CLIENT_SECRET: "xxxxxxxxxxxxxxxxxxxxxxxxx"
  REDIRECT_URL: "https://xxxxxxxxxx.appspot.com"
  DB_USER: "xxxxxx"
  DB_PASS: "xxxxxx"
  DB_NAME: "xxxxxx-db"
  INSTANCE_CONNECTION_NAME: "xxxxxx:europe-west2:xxxxxx-db"
```
