### ISSUE TITLE
Google Cloud Functions - private package in private repo?

### ISSUE THREAD

**Issue by techieshark** [GoogleCloudPlatform/nodejs-docs-samples#2193]
Is there an example showing how to deploy a cloud function which makes use of a private modules (from a private code repo, hosted as part of [GitHub package repository](https://github.com/features/packages))?

This is somewhat similar to #300 but should probably be reopened since that it has been about four years and we now know that [using private modules is possible](https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs#using_private_modules) but that example only covers NPM package repo, not GitHub.

Thanks!

**Comment by ace-n** [comment]
@techieshark have you tried configuring your `.npmrc` file as shown [here](https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#authenticating-with-a-personal-access-token)?

```
//npm.pkg.github.com/:_authToken=TOKEN
```

**Comment by techieshark** [comment]
@ace-n thanks for the response. Yes my .npmrc which is included in the deployed source is:
  
```
@myOrg:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=my-secret-auth-token
```

Unfortunately that doesn't work for me.

The full details of what I've tried and how it fails are shown here:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/258#issue-821970999

I've since then found [this issue](https://issuetracker.google.com/issues/147259775) in the Google Issue Tracker, and the fact that it is still open makes me suspect that this is simply not something that the cloud functions team has made to work yet (if so, perhaps that could be documented?)

**Comment by ace-n** [comment]
@techieshark thanks for the follow-up.

I've submitted a request internally to document this behavior.

cc @bcoe as FYI

**Comment by ace-n** [comment]
Documentation updated. 🙂

(It may take a few days for the update to be publicly visible.)

**Comment by techieshark** [comment]
Hi @ace-n - thanks or the super quick action! But... my apologies, but I may have been mistaken. 😬 

After following up on a tip from @grant I was able to dig into this issue further and it seemed like the module *was* installed, but it was just a misleading log entry that made me believe it wasn't. I hope the additional info in the comment below is helpful to you and/or others:

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/258#issuecomment-791850281

**Comment by ace-n** [comment]
@techieshark thanks for the follow-up, and I'm glad you were able to figure it out!

Given the public issue you linked above, I think more investigation is necessary. @bcoe is this something you can test out + report back on? (I don't have a private NPM repo handy.)

**Comment by bcoe** [comment]
These steps work for me, is there anything that could be updated accordingly in the samples?

## Using a Private Package in Cloud Function
 
1. [followed publishing a package tutorial](https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions#publishing-a-package-using-an-action), created the following automation:
  ```
    on:
    push:
        branches:
        - main
    name: release-please
    jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
        - uses: bcoe/release-please-action@v2
            id: release
            with:
            token: ${{ secrets.GITHUB_TOKEN }}
            release-type: node
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
            with:
            node-version: 14
        - run: npm install
        - uses: actions/setup-node@v1
            with:
            node-version: 14
            registry-url: https://npm.pkg.github.com/
            if: ${{ steps.release.outputs.release_created }}
        - run: npm install
            if: ${{ steps.release.outputs.release_created }}
        - run: npm publish
            env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            if: ${{ steps.release.outputs.release_created }}
  ```
2. Created a repository with `.npmrc` in root:
  ```
    //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
    @bcoe:registry=https://npm.pkg.github.com
  ```
3. Created access token with registry read permissions.
4. [Deployed function with gcloud](https://cloud.google.com/functions/docs/tutorials/http) with build environment variable `GITHUB_TOKEN` set to access token from prior step.
5. accessed function.
