### ISSUE TITLE
testing: Add support for runtime environment variables to GitHub Workflows

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#3501]
GitHub Workflows is the preferred test driver for tests in this repository, but the current workflow implementation has several limitations. One of them is the ability to set runtime environment variables that are specific to a Workflow.

## Approach

Options:
1. Hard code a central map of environment variables, and refactor code to ensure clean namespacing
2. Create a mechanism to pass environment variables to our reusable test workflow

Option 2 is the most versatile with the least need to refactor existing code.

Option 1 has the further downside of placing test-specific parameters in a central file. I'm not sure if any changes to `test.yml` are triggering wide-scale test execution currently, but with this approach we'd likely need to trigger more tests from any change, which would include adding environment variables for unrelated tests.

@pattishin  has asked that as part of the PR fixing this issue, we look for existing hard-coded values and shift them to environment variable configuration.

This issue is a blocker on implementation of GHA-based test workflows for a number of samples, with #3149 as the driver for research today.

**Comment by grayside** [comment]
Here are some notes towards Option 2 from the OP:

Illustrating the thought just a bit further (this is a thought experiment, not tested!)

in functions-v2-imagemagick.yaml:

Add a new job:
```
  setup:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
    - run: |
        echo "FUNCTIONS_BUCKET=nodejs-docs-samples-tests" >> $GITHUB_OUTPUT
        echo "BLURRED_BUCKET_NAME=nodejs-docs-samples-tests-imagick" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
```

Add use of this to the test job:

```
  test:
    # Ref: https://github.com/google-github-actions/auth#usage
    permissions:
      contents: 'read'
      id-token: 'write'
    if: github.event.action != 'labeled' || github.event.label.name == 'actions:force-run'
    uses: ./.github/workflows/test.yaml
    with:
      name: 'functions-v2-imagemagick'
      path: 'functions/v2/imagemagick'
      env: needs.setup.outputs
    needs: [setup]
```

In test.yaml add a new input:

```
      env:
        type: string
```

Then after the authentication step, load the environment from input to env:

```
    - name: Set caller env
      run: |
        echo "${{inputs.env}}" >> $GITHUB_ENV
```

If some variant of this works, we now have a way for the calling workflow to pass unexpected environment variables to the test workflow.
