### ISSUE TITLE
Admin Login example

### ISSUE THREAD

**Issue by pashaseliverstov** [GoogleCloudPlatform/nodejs-docs-samples#706]
in https://cloud.google.com/appengine/docs/standard/nodejs/config/appref
says

"login | The login element is not supported for Node.js in the standard environment. For user management you can use Cloud Identity and Access Management, see Access Control for details."

Please provide code examples for allowing access only for app admins.

**Comment by kmturley** [comment]
Also want an example of how this is done. And if we can secure headers using the app.yaml? e.g.

```
handlers:
- url: /.*
  secure: always
  login: admin
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"
```
